spring:
  redis:
    host: 127.0.0.1
    timeout: 3000
    database: 6
    jedis:
      pool:
        max-active: 10
        max-wait:  1000
        max-idle: 10
        min-idle: 2

logging:
  level:
    cn.ben.air.db.mapper: INFO
